# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🔢 Metrics
        uses: lowlighter/metrics@master
        with:
          # repositories_affiliations: ""
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
          repositories: 2000
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Token used for push
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          # If we want an org
          # user: bbenzikry
          # repo: 
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Asia/Jerusalem
          plugin_achievements: yes
          plugin_achievements_limit: 6
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          # plugin_notable: yes

          # plugin_followup: yes
#          plugin_introduction: yes
#          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_colors: rainbow
          # plugin_languages_threshold: 0%
          plugin_languages_limit: 0
          plugin_languages_details: percentage
          # removed lined for a more accurate description
          # plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
          
          # plugin_notable: yes
          # plugin_notable_filter: stars:>500
          # plugin_notable_repositories: yes
          config_order: base.activity,base.community,base.repositories,base.metadata, activity, languages, topics, stars, achievements
